name: Build
on: [pull_request]
permissions:
  contents: read

jobs:
  botpress:
    permissions:
      contents: none
    name: Botpress
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PIPELINE_TOKEN }}
          submodules: true
      - uses: actions/setup-node@v2
        with:
          node-version: '12.18.1'
          cache: 'yarn'
      - name: Fetch Node Packages
        run: |
          yarn --frozen-lockfile
      - name: Build Botpress
        run: yarn build --prod --linux
        env:
          NODE_OPTIONS: '--max-old-space-size=6000'
          EDITION: pro
